version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "**/v[0-9]*"
    labels:
      - dependencies
      - automated
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - automated
    open-pull-requests-limit: 5
